#! /usr/bin/env bash

function lb() {

  FILENAME=~/logbook/$(date '+%Y-%m-%d').md

  if [ ! -f $FILENAME ]; then
      touch $FILENAME
      cat << DOC > $FILENAME
Consider the problem you’re attempting to solve
-

Describe your method for solving it
-

Describe the process of carrying out the method
-

Record what happened, and ask how it could be improved
-
DOC
  fi
  vim $FILENAME
}
